version: '3.9'

services:
  loadbalancer:
    build:
      context: ./Traefik
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Traefik/config/traefik.yaml:/etc/traefik/traefik.yaml
      - ./Traefik/config/dynamic:/etc/traefik/dynamic
    depends_on:
      - web
    networks:
      - perfectly-balanced
  web:
    container_name: ostchat-web
    build:
      context: ./Website
      target: ${TARGET:-development}
    restart: "no"
    working_dir: /usr/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ostchat.entrypoints=web"
      - "traefik.http.routers.ostchat.rule=PathPrefix(`/`)"
    volumes:
      - ./Website/:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3030"
    depends_on:
      - db
    networks:
      - ostchat-backend-db
      - perfectly-balanced
  db:
    container_name: ostchat-database
    build:
      context: ./Database
      target: postgres-${TARGET:-development}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-ostchat}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    # TODO: Volume currently disabled to make it volatile. Uncomment to make it persistent.
    #volumes:
    #  - postgres-db:/var/lib/postgresql/data
    networks:
      - ostchat-backend-db
      - ostchat-db-pgadmin4

  pgadmin:
    container_name: ostchat-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE:-False}
    volumes:
      - ostchat-pgadmin:/var/lib/pgadmin
    networks:
      - ostchat-db-pgadmin4
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db

volumes:
  ostchat-pgadmin:


networks:
  ostchat-backend-db:
    ipam:
      driver: default
  ostchat-db-pgadmin4:
    ipam:
      driver: default
  perfectly-balanced:
    ipam:
      driver: default
